// NOTE: keys are autogenerated (based on SHA-1 of data)
// see: scripts/presets-with-ids.js
module.exports = (t) => ({
  "preset-bcdaf15": {
    "title": t("print-project.preset-bcdaf15-title"),
    "data": {
      "orientation": "landscape",
      "gridDim": [
        3,
        5
      ],
      "direction": "column",
      "enableDialogue": true,
      "enableAction": true,
      "enableNotes": true,
      "enableShotNumber": true,
      "boardTimeDisplay": "duration",
      "boardTextSize": 7,
      "boardBorderStyle": "minimal",
      "header": {
        "stats": {
          "boards": true,
          "shots": true,
          "sceneDuration": true,
          "aspectRatio": true,
          "dateExported": true
        }
      }
    }
  },
  "preset-ef6b965": {
    "title": t("print-project.preset-ef6b965-title"),
    "data": {
      "orientation": "landscape",
      "gridDim": [
        3,
        2
      ],
      "direction": "column",
      "enableDialogue": true,
      "enableAction": true,
      "enableNotes": true,
      "enableShotNumber": true,
      "boardTimeDisplay": "duration",
      "boardTextSize": 7,
      "boardBorderStyle": "minimal",
      "header": {
        "stats": {
          "boards": true,
          "shots": true,
          "sceneDuration": true,
          "aspectRatio": true,
          "dateExported": true
        }
      }
    }
  },
  "preset-9782c3c": {
    "title": t("print-project.preset-9782c3c-title"),
    "data": {
      "orientation": "landscape",
      "gridDim": [
        3,
        1
      ],
      "direction": "column",
      "enableDialogue": true,
      "enableAction": true,
      "enableNotes": true,
      "enableShotNumber": true,
      "boardTimeDisplay": "duration",
      "boardTextSize": 7,
      "boardBorderStyle": "full",
      "header": {
        "stats": {
          "boards": true,
          "shots": true,
          "sceneDuration": true,
          "aspectRatio": true,
          "dateExported": true
        }
      }
    }
  },
  "preset-f0b6ef5": {
    "title": t("print-project.preset-f0b6ef5-title"),
    "data": {
      "orientation": "landscape",
      "gridDim": [
        4,
        4
      ],
      "direction": "column",
      "enableDialogue": true,
      "enableAction": true,
      "enableNotes": true,
      "enableShotNumber": true,
      "boardTimeDisplay": "duration",
      "boardTextSize": 7,
      "boardBorderStyle": "minimal",
      "header": {
        "stats": {
          "boards": true,
          "shots": true,
          "sceneDuration": true,
          "aspectRatio": true,
          "dateExported": true
        }
      }
    }
  },
  "preset-97bdefb": {
    "title": t("print-project.preset-97bdefb-title"),
    "data": {
      "orientation": "landscape",
      "gridDim": [
        1,
        1
      ],
      "direction": "column",
      "enableDialogue": true,
      "enableAction": true,
      "enableNotes": true,
      "enableShotNumber": true,
      "boardTimeDisplay": "duration",
      "boardTextSize": 7,
      "boardBorderStyle": "minimal",
      "header": {
        "stats": {
          "boards": true,
          "shots": true,
          "sceneDuration": true,
          "aspectRatio": true,
          "dateExported": true
        }
      }
    }
  },
  "preset-07fa6ed": {
    "title": t("print-project.preset-07fa6ed-title"),
    "data": {
      "orientation": "landscape",
      "gridDim": [
        1,
        1
      ],
      "direction": "column",
      "enableDialogue": true,
      "enableAction": true,
      "enableNotes": true,
      "enableShotNumber": true,
      "boardTimeDisplay": "none",
      "boardTextSize": 7,
      "boardBorderStyle": "minimal",
      "header": {
        "stats": {
          "boards": false,
          "shots": false,
          "sceneDuration": false,
          "aspectRatio": false,
          "dateExported": true
        }
      }
    }
  },
  "preset-3c3532b": {
    "title": t("print-project.preset-3c3532b-title"),
    "data": {
      "orientation": "landscape",
      "gridDim": [
        2,
        2
      ],
      "direction": "column",
      "enableDialogue": false,
      "enableAction": false,
      "enableNotes": false,
      "enableShotNumber": false,
      "boardTimeDisplay": "none",
      "boardTextSize": 7,
      "boardBorderStyle": "minimal",
      "header": {
        "stats": {
          "boards": true,
          "shots": true,
          "sceneDuration": true,
          "aspectRatio": true,
          "dateExported": true
        }
      }
    }
  },
  "preset-7415d88": {
    "title": t("print-project.preset-7415d88-title"),
    "data": {
      "orientation": "landscape",
      "gridDim": [
        3,
        3
      ],
      "direction": "column",
      "enableDialogue": false,
      "enableAction": false,
      "enableNotes": false,
      "enableShotNumber": false,
      "boardTimeDisplay": "none",
      "boardTextSize": 7,
      "boardBorderStyle": "minimal",
      "header": {
        "stats": {
          "boards": true,
          "shots": true,
          "sceneDuration": true,
          "aspectRatio": true,
          "dateExported": true
        }
      }
    }
  },
  "preset-110b5e4": {
    "title": t("print-project.preset-110b5e4-title"),
    "data": {
      "orientation": "landscape",
      "gridDim": [
        6,
        5
      ],
      "direction": "column",
      "enableDialogue": false,
      "enableAction": false,
      "enableNotes": false,
      "enableShotNumber": false,
      "boardTimeDisplay": "none",
      "boardTextSize": 7,
      "boardBorderStyle": "minimal",
      "header": {
        "stats": {
          "boards": true,
          "shots": true,
          "sceneDuration": true,
          "aspectRatio": true,
          "dateExported": true
        }
      }
    }
  },
  "preset-8949e51": {
    "title": t("print-project.preset-8949e51-title"),
    "data": {
      "orientation": "portrait",
      "gridDim": [
        1,
        5
      ],
      "direction": "row",
      "enableDialogue": true,
      "enableAction": true,
      "enableNotes": true,
      "enableShotNumber": true,
      "boardTimeDisplay": "duration",
      "boardTextSize": 7,
      "boardBorderStyle": "full",
      "header": {
        "stats": {
          "boards": true,
          "shots": true,
          "sceneDuration": true,
          "aspectRatio": true,
          "dateExported": true
        }
      }
    }
  },
  "preset-4feebf9": {
    "title": t("print-project.preset-4feebf9-title"),
    "data": {
      "orientation": "landscape",
      "gridDim": [
        1,
        5
      ],
      "direction": "row",
      "enableDialogue": true,
      "enableAction": true,
      "enableNotes": true,
      "enableShotNumber": true,
      "boardTimeDisplay": "duration",
      "boardTextSize": 7,
      "boardBorderStyle": "full",
      "header": {
        "stats": {
          "boards": true,
          "shots": true,
          "sceneDuration": true,
          "aspectRatio": true,
          "dateExported": true
        }
      }
    }
  },
  "preset-e32799a": {
    "title": t("print-project.preset-e32799a-title"),
    "data": {
      "orientation": "landscape",
      "gridDim": [
        4,
        2
      ],
      "direction": "column",
      "enableDialogue": true,
      "enableAction": true,
      "enableNotes": true,
      "enableShotNumber": true,
      "boardTimeDisplay": "none",
      "boardTextSize": 7,
      "boardBorderStyle": "minimal",
      "header": {
        "stats": {
          "boards": false,
          "shots": false,
          "sceneDuration": false,
          "aspectRatio": false,
          "dateExported": true
        }
      }
    }
  },
  "preset-d11d6df": {
    "title": t("print-project.preset-d11d6df-title"),
    "data": {
      "orientation": "portrait",
      "gridDim": [
        4,
        3
      ],
      "direction": "column",
      "enableDialogue": true,
      "enableAction": true,
      "enableNotes": true,
      "enableShotNumber": true,
      "boardTimeDisplay": "none",
      "boardTextSize": 7,
      "boardBorderStyle": "minimal",
      "header": {
        "stats": {
          "boards": false,
          "shots": false,
          "sceneDuration": false,
          "aspectRatio": false,
          "dateExported": true
        }
      }
    }
  },
  "preset-49b851f": {
    "title": t("print-project.preset-49b851f-title"),
    "data": {
      "orientation": "landscape",
      "gridDim": [
        2,
        1
      ],
      "direction": "column",
      "enableDialogue": true,
      "enableAction": true,
      "enableNotes": true,
      "enableShotNumber": true,
      "boardTimeDisplay": "none",
      "boardTextSize": 7,
      "boardBorderStyle": "minimal",
      "header": {
        "stats": {
          "boards": false,
          "shots": false,
          "sceneDuration": false,
          "aspectRatio": false,
          "dateExported": true
        }
      }
    }
  },
  "preset-6df1a27": {
    "title": t("print-project.preset-6df1a27-title"),
    "data": {
      "orientation": "portrait",
      "gridDim": [
        2,
        4
      ],
      "direction": "column",
      "enableDialogue": true,
      "enableAction": true,
      "enableNotes": true,
      "enableShotNumber": true,
      "boardTimeDisplay": "none",
      "boardTextSize": 7,
      "boardBorderStyle": "minimal",
      "header": {
        "stats": {
          "boards": false,
          "shots": false,
          "sceneDuration": false,
          "aspectRatio": false,
          "dateExported": true
        }
      }
    }
  }
}
)
