
let alternateValues = {
  ecu: ['extra close', 'extreme close', 'xcu'],
  vcu: ['very close'],
  cu: ['close', 'close-up', 'closeup'],
  mcu: ['medium close', 'medium close-up', 'medium closeup'],
  ms: ['medium', 'medium shot', 'waist', 'mid', 'med'],
  mls: ['medium long', 'three quarters', 'threequarters'],
  ls: ['long', 'full', 'wide shot', 'long shot', 'ws'],
  els: ['extreme long', 'exteme full', 'extreme wide shot', 'ews'],
  oneShot: ['single person', 'one shot', 'single', '1s'],
  twoShot: ['double', '2s'],
  threeShot: ['triple', '3s'],
  ots: ['over the shoulder', 'over shoulder', 'ab tu', 'third person'],
  groupShot: ['group', 'gs'],
  left: ['left angle'],
  right: ['right angle'],
  center: ['centered'],
  birdsEye: ['birdseye', 'be', 'aerial', 'top'],
  high: ['high angle', 'ha'],
  eye: ['eye level', 'el'],
  low: ['low angle', 'la'],
  wormsEye: ['wormseye', 'we', 'floor'],
  ultraWide: ['extreme wide lens', 'ultra wide lens'],
  wide: ['wide lens', 'wide angle'],
  medium: ['medium lens'],
  long: ['long lens', 'telephoto'],
  headFront: ['looking forward', 'looking front', 'looking straight', 'facing forward', 'facing front', 'facing straight', 'head front', 'head straight', 'head forward'],
  headUp: ['looking up', 'facing up', 'head up'],
  headDown: ['looking down', 'facing down', 'head down'],
  headLeft: ['looking left', 'facing left', 'head left'],
  headRight: ['looking right', 'facing right', 'head right'],
  abovelit: ['toplit', 'lit from above'],
  underlit: ['bottomlit', 'lit from below'],
  silhouette: ['siloette', 'silhoette', 'silo'],
  auditorium: ['stadium', 'concert'],
  run: ['jog'],
  sit_in_chair: ['sitting'],
  hunch_over: ['hunched', 'sad', 'sick'],
  cross_arms: ['crossing'],
  lean_back: ['leaning'],
  hold_something: ['holding'],
  turn_around: ['turning'],
  sit_on_floor: ['sitting on floor'],
  on_back: ['laying'],
}

module.exports = alternateValues